UseCaseManagement/force-app/main/default/objects/Campaign/fields/Current_Region__c.field-meta.xml
<CustomField>
    <fullName>Current_Region__c</fullName>
    <label>Current Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>Central and Eastern Europe</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Mediterranean &amp; Middle East</fullName>
            </value>
            <value>
                <fullName>Americas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Campaign/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Campaign/fields/Publication_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Publication_Cycle__c</fullName>
    <label>Publication Cycle</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/Publication__c.object-meta.xml
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Cost_of_Publication__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Publication__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost of Publication</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Publication_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Publication_Cycle__c</fullName>
    <label>Publication Cycle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Publication_Language__c.field-meta.xml
<CustomField>
    <fullName>Publication_Language__c</fullName>
    <label>Publication Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Publication_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Publication_Revenue__c</fullName>
    <formula>Cost_of_Publication__c  *  No_of_Campaign_elements__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Publication Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Publication_Type__c.field-meta.xml
<CustomField>
    <fullName>Publication_Type__c</fullName>
    <label>Publication Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/objects/Publication__c/fields/Region_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Region_of_Operation__c</fullName>
    <label>Region of Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>Central and Eastern Europe</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Mediterranean &amp; Middle East</fullName>
            </value>
            <value>
                <fullName>Americas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

UseCaseManagement/force-app/main/default/classes/PublicationController.cls
public class PublicationController
{
    private  Campaign Camp;
     public PublicationController(ApexPages.StandardController Campaign) {

        this.camp = (Campaign)Campaign.getRecord();
         camp = [select Language__c, Current_Region__c from campaign where id=:camp.id];
         search();
     }

   public List<Publication__c> PublicationRecords {get;set;}
    public List<Campaign> CampaignRecords {get;set;}
    public void search()
        {
            List<string> lang = new list<string>();
            lang=camp.Language__c.split(';');
                       
            //CampaignRecords= [SELECT Language__c,Current_Region__c FROM Campaign LIMIT 100];
            PublicationRecords= [SELECT Name,Publication_Type__c,Publication_Cycle__c, Publication_Language__c, Cost_of_Publication__c, Publication_Revenue__c, Region_of_Operation__c FROM Publication__c WHERE Publication_Language__c =:lang LIMIT 1000];
        }
    
}